import { useState } from 'react';
import { ArrowRight, BrainCircuit, ChevronRight, Clock3, Code2, Cpu, FileText, Laptop, Lightbulb, Menu, Network, Presentation, Send, Settings, Sparkles, Trophy, Users, X } from 'lucide-react';
import { useEventNavigation } from '../components/EventNavigation';
import './styles/ai-battle-exact.css';

const formatSteps = [['Problem Statement', 'Theme or problem statement will be given on the spot.', FileText], ['Task', 'Design and develop an application for the given theme.', Lightbulb], ['Technology', 'Any language, framework, AI tool, API or open-source technology.', Code2], ['Development', 'Design, develop, test and complete within 1 hr 30 mins.', Settings], ['Application', 'A working end-to-end solution is required.', Network], ['Submission', 'Submit the completed application at the end of the event.', Send], ['Demo', 'Demonstrate the application to the judges.', Presentation]];
const criteria = [['Innovation & Creativity', Sparkles], ['AI Implementation', BrainCircuit], ['Technical Implementation', Code2], ['Functionality & Working', Settings], ['UI/UX & User Experience', Users], ['Presentation & Demo', Presentation]];

export function AIBattleExactPage() {
  const { goHome, goRegister } = useEventNavigation(); const [menuOpen, setMenuOpen] = useState(false);
  const scrollTo = (id) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); };
  return <main className="ai-reference-page">
    <header className="ai-reference-topbar"><div className="ai-reference-nav"><button className="ai-reference-brand" onClick={goHome} type="button"><img src="/fenix-26-logo.jpg" alt="FENIX 2026" /> FENIX'26</button><nav className={menuOpen ? 'ai-reference-links open' : 'ai-reference-links'}><button onClick={goHome} type="button">Home</button><button onClick={() => scrollTo('format')} type="button">Format</button><button onClick={() => scrollTo('contact')} type="button">Contact</button></nav><button className="ai-reference-register" onClick={goRegister} type="button">Register Now <ArrowRight size={17} /></button><button className="ai-reference-menu" onClick={() => setMenuOpen(!menuOpen)} type="button" aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button></div></header>
    <section className="ai-reference-hero"><div className="ai-reference-hero-inner"><div className="ai-reference-eyebrow"><Cpu size={20} /> AI BATTLE</div><h1><span>AI</span> BATTLE</h1><p>BUILD <i>/</i> CODE <i>/</i> INNOVATE</p><div className="ai-reference-facts"><span><Laptop /> Laptop</span><span><Clock3 /> 1 hr 30 mins</span></div></div></section>
    <section id="format" className="ai-reference-content"><article className="ai-reference-panel ai-reference-format"><div className="ai-reference-heading"><Code2 /> EVENT FORMAT</div><h2>Rapid Application Development</h2><div className="ai-reference-steps">{formatSteps.map(([title, text, Icon], index) => <div className="ai-reference-step" key={title}><span className="ai-reference-number">{index + 1}</span><span className="ai-reference-icon"><Icon size={25} /></span><span><strong>{title}</strong><small>{text}</small></span></div>)}</div></article><article className="ai-reference-panel ai-reference-criteria"><div className="ai-reference-heading pink"><Trophy /> EVALUATION CRITERIA</div><div>{criteria.map(([title, Icon]) => <div className="ai-reference-criterion" key={title}><span><Icon size={28} /></span><strong>{title}</strong></div>)}</div></article></section>
    <section className="ai-reference-quote"><p><span>Think Fast..!!</span> <b>Build Smart..!!</b><br /><em>Battle with AI..!!</em> <Trophy size={29} /></p></section>
    <footer id="contact" className="ai-reference-footer"><div className="ai-reference-footer-grid"><div className="ai-reference-footer-brand"><img src="/fenix-26-logo.jpg" alt="FENIX 2026" /><strong>FENIX'26</strong></div><div className="ai-reference-quick"><h3>Quick Links</h3><button onClick={goHome} type="button">Home <ChevronRight size={15} /></button><button onClick={() => scrollTo('format')} type="button">Format <ChevronRight size={15} /></button><button onClick={() => scrollTo('contact')} type="button">Contact <ChevronRight size={15} /></button></div><div className="ai-reference-contacts"><h3>Contact</h3><a href="tel:+918220367554"><strong>Santhiya S</strong><small>+91 82203 67554</small></a><a href="tel:+918489387739"><strong>Muthuraja P</strong><small>+91 84893 87739</small></a></div></div><small>© 2026 FENIX'26. All Rights Reserved.</small></footer>
  </main>;
}
