import { useState } from 'react';
import { ArrowRight, Check, ChevronRight, Clock3, Gamepad2, Menu, MonitorSmartphone, Phone, ShieldAlert, ShieldX, Skull, Smartphone, Sword, Trophy, Users, X } from 'lucide-react';
import { useEventNavigation } from '../components/EventNavigation';
import './styles/free-fire-exact.css';

const steps = [['Squad briefing', '4 members', Users], ['Knockout match', 'Battle Royale / Clash Squad', Gamepad2], ['Final battle', 'Winner takes the crown', Trophy]];
const requirements = ['Register as a 4-member squad', 'Mobile device required', 'Battle Royale or Clash Squad mode, based on participating teams', 'Knockout format — losing teams are eliminated', 'Non-FENIX’26 participants may enter with an additional ₹50 fee', 'A rematch after elimination requires a new ₹50 entry fee, subject to availability'];
const restrictions = ['Hacks, panels, scripts, or unfair third-party tools', 'Wall-breaking or wall-glitch techniques', 'Gun skins', 'Roof camping or camping in prohibited locations', 'Anything other than direct attacks', 'Rule violations — immediate disqualification'];

function SectionTitle({ children }) { return <div className="ffx-section-title"><i /><h2>{children}</h2></div>; }
export function FreeFirePage() {
  const { goHome, goRegister } = useEventNavigation(); const [menuOpen, setMenuOpen] = useState(false);
  const scrollTo = (id) => { setMenuOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const links = [['Home', 'ffx-home'], ['Format', 'ffx-format'], ['Rules', 'ffx-rules'], ['Rewards', 'ffx-rewards']];
  return <main className="ffx-page"><div className="ffx-ambient ffx-ambient-one" aria-hidden="true" /><div className="ffx-ambient ffx-ambient-two" aria-hidden="true" /><div className="ffx-shell">
    <header className="ffx-nav"><button className="ffx-brand" type="button" onClick={goHome}><img src="/images/fenix-logo.jpeg" alt="" />FENIX<span>'26</span></button><nav className={menuOpen ? 'ffx-links open' : 'ffx-links'} aria-label="Free Fire navigation">{links.map(([label, id]) => <button key={id} type="button" onClick={() => scrollTo(id)}>{label}</button>)}</nav><button className="ffx-register" type="button" onClick={goRegister}>Register Now <ArrowRight size={15} /></button><button className="ffx-menu" type="button" aria-label="Toggle menu" aria-expanded={menuOpen} onClick={() => setMenuOpen((open) => !open)}>{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>
    <section className="ffx-hero" id="ffx-home"><img src="/images/free-fire-hero.png" alt="Free Fire battle scene" /><div className="ffx-hero-overlay" /><div className="ffx-hero-copy"><span className="ffx-pill"><i /> Squad battle</span><h1>FREE FIRE</h1><p className="ffx-tagline">Battle Royale / Clash Squad</p><p className="ffx-description">Bring a 4-member squad, survive the knockout, and claim the battlefield.</p><div className="ffx-chips"><span><Users size={16} /> 4 members</span><span><Clock3 size={16} /> 40 minutes</span><span><MonitorSmartphone size={16} /> Mobile required</span></div><div className="ffx-actions"><button type="button" onClick={goRegister}>Register Now <ArrowRight size={16} /></button><button type="button" onClick={() => scrollTo('ffx-rules')}>View rules</button></div></div></section>
    <section className="ffx-panel" id="ffx-format"><SectionTitle>Match format</SectionTitle><ol className="ffx-flow">{steps.map(([label, detail, Icon], index) => <li key={label}><div><span><Icon size={20} /></span><p>Stage {index + 1}</p><strong>{label}<small>{detail}</small></strong></div>{index < steps.length - 1 && <ChevronRight className="ffx-flow-arrow" size={20} />}</li>)}</ol></section>
    <section className="ffx-rules" id="ffx-rules"><article className="ffx-panel"><SectionTitle>Rules</SectionTitle><div className="ffx-rule-columns"><div><h3>Match conditions</h3><ul>{requirements.map((label) => <li key={label}><span><Check size={16} /></span><b>{label}</b></li>)}</ul></div><div><h3 className="danger">Not allowed</h3><ul>{restrictions.map((label) => <li className="not-allowed" key={label}><span><ShieldX size={16} /></span><b>{label}</b></li>)}</ul></div></div></article></section>
    <section className="ffx-panel ffx-rewards" id="ffx-rewards"><SectionTitle>Rewards</SectionTitle><div><article><Trophy size={25} /><small>🥇 Winner</small><strong>₹1,000</strong></article><article><Sword size={25} /><small>🥈 Runner-up</small><strong>₹500</strong></article></div><p><ShieldAlert size={16} /> Participants who are not registered for FENIX’26 can participate with an additional ₹50 entry fee.</p></section>
    <button className="ffx-main-cta" type="button" onClick={goRegister}>Register your squad <ArrowRight size={16} /></button>
    <footer className="ffx-footer ffx-panel"><div><div className="ffx-footer-brand"><img src="/images/fenix-logo.jpeg" alt="" />FENIX<span>'26</span></div><p>Drop In..!! Frag Out..!! Dominate the Battlefield..!!</p></div><div><h3>Quick links</h3>{links.map(([label, id]) => <button key={id} type="button" onClick={() => scrollTo(id)}>{label}</button>)}</div><div className="ffx-event-contact"><h3>Contact</h3><a href="tel:+918270528707"><strong>Sangeetha J</strong><small><Phone size={12} /> +91 82705 28707</small></a><a href="tel:+916381429220"><strong>Indra Santhoshi B</strong><small><Phone size={12} /> +91 63814 29220</small></a></div><div className="ffx-copyright"><span>© 2026 FENIX'26. All rights reserved.</span><span>Made for gamers, by gamers.</span></div></footer>
  </div></main>;
}
