import { useState } from 'react';
import { ArrowRight, BadgeCheck, Check, ChevronRight, ClipboardList, Gavel, Menu, Scale, Tag, Target, Trophy, Users, Wallet, X } from 'lucide-react';
import { useEventNavigation } from '../components/EventNavigation';
import { EventBackButton } from '../components/EventBackButton';
import './styles/ipl-auction-exact.css';

const steps = [[Users, '5 Members'], [Tag, '160 Players'], [Gavel, '20 Superstars'], [BadgeCheck, 'Bidding'], [Trophy, '16-Player Squad']];
const rules = ['Franchise-based auction: every franchise has 5 members.', 'Each team receives a total purse of ₹60 Crore.', '160 players are available; round one auctions 20 superstar players.', 'Bid through multiple rounds until all required squad slots are filled.', 'Every franchise must complete all 16 player slots within the ₹60 Crore purse.', 'A maximum of 5 overseas players can be selected.', 'Focus on Playing 11, budget management, player selection, auction strategy and squad balance.', 'Final ranking considers Playing 11, budget management, player selection and player variety.', 'Top 3 teams receive 1st, 2nd and 3rd place.'];
const evaluations = [[ClipboardList, 'Playing 11', 'Build a balanced and effective core team.'], [Scale, 'Budget Management', 'Use the ₹60 Crore purse wisely.'], [Target, 'Player Selection', 'Choose the right players and variety.'], [Trophy, 'Auction Strategy', 'Build a complete 16-player squad.']];

function Heading({ children }) { return <div className="iplx-heading"><i /><h2>{children}</h2></div>; }

export function IPLAuctionExactPage() {
  const { goHome, goRegister } = useEventNavigation();
  const [menuOpen, setMenuOpen] = useState(false);
  const jump = (id) => { setMenuOpen(false); document.getElementById(`iplx-${id}`)?.scrollIntoView({ behavior: 'smooth' }); };
  return <main className="iplx-page"><div className="iplx-shell"><div className="iplx-glow one" /><div className="iplx-glow two" />
    <header className="iplx-nav"><button className="iplx-brand" type="button" onClick={goHome}><img src="/fenix-26-logo.jpg" alt="FENIX 2026" /><span>FENIX<span>'26</span></span></button><nav className={menuOpen ? 'iplx-links open' : 'iplx-links'}><button type="button" onClick={goHome}>Home</button><button type="button" onClick={() => jump('rules')}>Rules</button><button type="button" onClick={() => jump('evaluation')}>Evaluation</button><button type="button" onClick={() => jump('contact')}>Contact</button></nav><button className="iplx-register" type="button" onClick={goRegister}>Register Now <ArrowRight size={15} /></button><button className="iplx-menu" type="button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle menu">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button></header>
    <div className="iplx-content"><section className="iplx-hero" id="iplx-home"><img className="iplx-hero-image" src="/images/ipl-auction-hero.png" alt="Golden auction gavel and cricket stadium" /><div className="iplx-hero-overlay" /><div className="iplx-hero-copy"><div className="iplx-hero-topline"><EventBackButton /><span className="iplx-pill"><i /> Non-Tech Event</span></div><h1><em>IPL</em> AUCTION</h1><h3>Build Your Championship Squad.</h3><p>Think strategically. Manage your budget. Build the winning team, position by position. Step into the shoes of an IPL franchise owner and out-bid your rivals.</p><div className="iplx-team"><Users size={16} /> Team Event <small>(5 Members)</small></div><div className="iplx-actions"><button type="button" onClick={goRegister}>Register Now <ArrowRight size={16} /></button><button type="button" onClick={() => jump('rules')}><Gavel size={16} /> Rules &amp; Details</button></div></div></section>
      <section className="iplx-section" id="iplx-auction-flow"><Heading>Auction Flow</Heading><div className="iplx-flow">{steps.map(([Icon, label], index) => <div key={label}><div><Icon size={21} /></div><b>{label}</b>{index < steps.length - 1 && <ChevronRight className="flow-arrow" size={18} />}</div>)}</div></section>
      <section className="iplx-section" id="iplx-key-rules"><Heading>Key Rules</Heading><div className="iplx-key-grid"><article className="do"><h3><Check size={18} /> Do</h3><p><Check size={15} /> Bid strategically</p><p><Check size={15} /> Manage your purse</p><p><Check size={15} /> Follow squad requirements</p></article><article className="dont"><h3><X size={18} /> Don&apos;t</h3><p><X size={15} /> Exceed budget</p><p><X size={15} /> Reverse a purchase</p><p><X size={15} /> Violate squad requirements</p></article><article className="purse"><h3><Wallet size={17} /> Virtual Purse</h3><strong>₹ 80 CR</strong><div><i /></div><p>₹ 72 CR <small>remaining</small></p></article></div></section>
      <section className="iplx-section" id="iplx-rules"><Heading>Event Rules</Heading><div className="iplx-event-rules"><div className="iplx-rule-meta"><span><Gavel size={15} /> Team Event</span><span><Users size={15} /> Suggested Team Size: 10 Members</span></div><ol>{rules.map((rule, index) => <li key={rule}><b>{index + 1}</b><span>{rule}</span></li>)}</ol></div></section>
      <section className="iplx-section" id="iplx-evaluation"><Heading>Evaluation Criteria</Heading><div className="iplx-evals">{evaluations.map(([Icon, title, desc]) => <article key={title}><span><Icon size={21} /></span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
      <section className="iplx-register-panel" id="iplx-register"><h2>Ready to build your championship squad?</h2><p>Raise your paddle, own the game. Register for the FENIX&apos;26 IPL Auction.</p><button type="button" onClick={goRegister}>Register Now <ArrowRight size={16} /></button></section></div>
    <footer className="iplx-footer" id="iplx-contact"><div><button className="iplx-footer-brand" onClick={goHome} type="button"><img src="/fenix-26-logo.jpg" alt="FENIX 2026" /><span>FENIX<span>'26</span></span></button><p>Raise your paddle, own the game. Build the winning squad at FENIX&apos;26 IPL Auction.</p></div><div><h3>Menu</h3><button onClick={goHome} type="button">Home</button><button onClick={() => jump('rules')} type="button">Rules</button><button onClick={() => jump('contact')} type="button">Contact</button></div><div className="iplx-contacts"><h3>Contact</h3><a href="tel:+919025528451"><span><strong>Deepan Raja S</strong><small>Event Incharge<br />+91 90255 28451</small></span></a><a href="tel:+918270528707"><span><strong>Sangeetha J</strong><small>Non Tech Coordinator<br />+91 82705 28707</small></span></a></div><small className="iplx-copy">© 2026 FENIX&apos;26. All rights reserved.</small></footer>
  </div></main>;
}
