import { Award, Check, Clock3, Laptop, LayoutDashboard, Palette, Phone, Route, Sparkles, Wand2, X } from 'lucide-react';
import { useEventNavigation } from '../components/EventNavigation';
import { EventBackButton } from '../components/EventBackButton';
import './styles/pixel-perfect-exact.css';
import './styles/pixel-perfect-spacing.css';

const flow = [['01', 'Understand the theme', '5 min', Sparkles], ['02', 'UI design & development', '45 min', Palette], ['03', 'Prototype & submit', '10 min', Route]];
const focusAreas = ['Layout', 'Spacing & Alignment', 'Typography', 'Colors', 'Icons & Images', 'UI Components', 'Visual Consistency', 'Creativity & Design Thinking', 'User Flow & Navigation', 'Overall User Experience'];
const evaluation = ['UI/UX quality & visual appeal', 'Layout, spacing & alignment', 'Typography & color selection', 'Component & design consistency', 'Creativity & theme interpretation', 'Prototype interactions & navigation', 'User flow & usability', 'Completion within 60 minutes'];
function Brand() { return <div className="brand"><img className="brand-logo" src="/fenix-26-logo.jpg" alt="FENIX 2026" /><span>FENIX<span className="brand-year">’26</span></span></div>; }

export function PixelPerfectExactPage() {
  const { goHome, goRegister } = useEventNavigation();
  const jump = (id) => document.getElementById(`pixel-${id}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  return <main className="pixel-exact-page"><div className="site-shell">
    <div className="ambient ambient-one" aria-hidden="true" /><div className="ambient ambient-two" aria-hidden="true" />
    <header className="topbar"><button className="brand brand-button" onClick={goHome} type="button"><Brand /></button><nav aria-label="Pixel Perfect navigation"><button className="nav-link active" onClick={goHome} type="button">Home</button><button className="nav-link" onClick={() => jump('challenge')} type="button">Challenge</button><button className="nav-link" onClick={() => jump('rules')} type="button">Rules</button><button className="nav-link" onClick={() => jump('evaluation')} type="button">Evaluation</button></nav><button className="register-button" onClick={goRegister} type="button">Register Now <span>→</span></button></header>
    <section id="pixel-home" className="hero reveal visible"><div className="hero-grid" aria-hidden="true" /><div className="hero-copy"><EventBackButton /><div className="eyebrow"><span>◉</span> TECHNICAL EVENT</div><h1>PIXEL PERFECT</h1><p className="hero-sub">Think It. Design It. Connect It.</p><p className="hero-note">Create a clear, connected 3–4 screen Figma prototype from a live theme.</p></div><div className="figma-orbit" aria-hidden="true"><div className="figma-card"><span className="figma-dot pink" /><span className="figma-dot orange" /><span className="figma-dot purple" /><span className="figma-dot blue" /><span className="figma-dot green" /></div><span className="orbit-dot">✦</span><span className="cursor">◢</span></div></section>
    <section className="highlight-row" aria-label="Event highlights"><div className="highlight"><span className="highlight-icon"><Laptop size={15} /></span><span><b>Laptop</b><small>Required</small></span></div><div className="highlight"><span className="highlight-icon"><Clock3 size={15} /></span><span><b>60 Minutes</b><small>Single round</small></span></div><div className="highlight"><span className="highlight-icon"><Palette size={15} /></span><span><b>Figma only</b><small>Design + prototype</small></span></div><div className="highlight"><span className="highlight-icon"><LayoutDashboard size={15} /></span><span><b>3–4 screens</b><small>Connected flow</small></span></div></section>
    <div className="section-layout pixel-rule-layout">
      <section id="pixel-challenge" className="challenge-panel reveal"><div className="section-label"><span>◌</span> Challenge</div><h2>One theme. One working prototype.</h2><p>Use the organizer-provided theme to conceptualize, design, and connect a coherent 3–4 screen interface in Figma.</p><div className="flow-grid">{flow.map(([number, label, time, Icon]) => <article key={number}><span>{number}</span><Icon size={19} /><strong>{label}</strong><small>{time}</small></article>)}</div><div className="prototype-callout"><Route size={18} /><span><b>Prototype challenge</b>Connect screens with Figma Prototype interactions, navigation, and transitions to create a functional user flow.</span></div></section>
      <aside className="criteria-panel reveal"><div className="section-label"><span>◈</span> Focus areas</div><div className="focus-list">{focusAreas.map((area) => <span key={area}>{area}</span>)}</div></aside>
      <section id="pixel-rules" className="rules-panel reveal"><article><div className="section-label"><span>✦</span> Deliverable</div><h2>Design, connect, submit.</h2><ul><li><Check size={14} /> Build 3–4 screens in Figma.</li><li><Check size={14} /> Maintain one clear user flow.</li><li><Check size={14} /> Use interactions and transitions in Figma Prototype.</li><li><Check size={14} /> Complete and submit within 60 minutes.</li></ul></article><article className="ai-policy"><div className="section-label"><span>✦</span> AI policy</div><h2><X size={18} /> No AI assistance</h2><p>AI tools, AI-generated designs, design-generation tools, and external AI assistance are strictly prohibited. All work must be created during the event.</p></article></section>
      <section id="pixel-evaluation" className="evaluation-panel reveal"><div className="section-label"><span>◈</span> Evaluation · 100 marks</div><div>{evaluation.map((item, index) => <span key={item}><b>{String(index + 1).padStart(2, '0')}</b>{item}</span>)}</div><p>Strong design thinking, visual consistency, prototype functionality, and timely completion determine the final ranking. The top three participants or teams receive 1st, 2nd, and 3rd place.</p></section>
    </div>
    <div className="pixel-final-callout"><Award size={20} /> Think It..!! Design It..!! Connect It..!! Make It Work..!! Think in Pixels..!!</div><button className="pixel-register-cta" type="button" onClick={goRegister}>Register for Pixel Perfect <span>→</span></button>
    <footer className="footer pixel-footer-compact"><div><Brand /><p>Design the flow.<br />Make it work.</p><small>© 2026 FENIX’26. All rights reserved.</small></div><div className="footer-links"><b>Quick Links</b><button onClick={goHome} type="button">Home</button><button onClick={() => jump('challenge')} type="button">Challenge</button><button onClick={() => jump('rules')} type="button">Rules</button><button onClick={() => jump('evaluation')} type="button">Evaluation</button></div><div className="pixel-event-contacts"><b>Contact</b><a href="tel:+918610334691"><strong>Vishnu Priya K</strong><small>Event Incharge<br /><Phone size={12} /> +91 86103 34691</small></a><a href="tel:+918489387739"><strong>Muthuraja P</strong><small>Tech Coordinator<br /><Phone size={12} /> +91 84893 87739</small></a></div></footer>
  </div></main>;
}
