export const eventsConfig = {
  'pixel-perfect': {
    slug: 'pixel-perfect',
    title: 'PIXEL PERFECT',
    subtitle: 'Replicate. Refine. Perfect.',
    category: 'Technical',
    icon: '◐',
    color: 'pink',
    tagline: 'Digital Design Studio',
    theme: { primary: '#ec4899', accent: '#f9a8d4', bg: '#1a0a14', glow: 'rgba(236,72,153,.3)' },
    eventType: 'Individual / Team of 2–4 Members',
    requirement: 'Laptop Required',
    duration: '2–2.5 Hours',
    roundDuration: 'Round 1: 30 Minutes · Round 2: 2 Hours',
    tool: 'Figma Only',
    aiNote: 'No AI Tools',
    heroVisual: 'design-studio',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'rounds', label: 'Rounds' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'submission', label: 'Submission' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Individual / Team (2–4)' },
      { label: 'Duration', value: '2–2.5 Hours' },
      { label: 'Tool', value: 'Figma Only' },
      { label: 'AI Tools', value: 'Prohibited' },
    ],
    overview: 'Pixel Perfect challenges your ability to replicate a UI design with pixel-level accuracy, then build a multi-screen interactive prototype. Test your eye for detail, spacing, typography, and color — and prove you can ship production-ready Figma files.',
    rounds: [
      {
        number: '01',
        title: 'The Blueprint Copy',
        duration: '30 Minutes',
        description: 'You are given a reference screenshot of a UI screen. Replicate it as closely as possible in Figma. Every pixel matters.',
        highlights: ['Reference screenshot provided', 'Match layout, spacing, and typography', 'Color accuracy from hex values', 'Speed bonus for early completion'],
        evaluationTitle: 'Evaluation Criteria',
        evaluation: [
          { label: 'Layout Understanding', weight: 'High' },
          { label: 'Visual Accuracy', weight: 'High' },
          { label: 'Spacing & Alignment', weight: 'High' },
          { label: 'Typography & Colors', weight: 'Medium' },
          { label: 'Speed of Execution', weight: 'Medium' },
        ],
        prototype: 'Not required in Round 1.',
      },
      {
        number: '02',
        title: 'The Flow Mimic',
        duration: '2 Hours',
        description: 'Design five connected screens as a working interactive prototype. Show real interactions, transitions, and navigation flow between screens.',
        highlights: ['5 connected screens required', 'Interactive prototype (Figma Prototype mode)', 'Demonstrate transitions and animations', 'User flow must be intuitive'],
        evaluationTitle: 'Evaluation Criteria',
        evaluation: [
          { label: 'Prototype Functionality', weight: 'High' },
          { label: 'Interaction Design', weight: 'High' },
          { label: 'Visual Consistency', weight: 'High' },
          { label: 'UX Flow & Navigation', weight: 'Medium' },
          { label: 'Animation Quality', weight: 'Medium' },
        ],
        prototype: 'The final 5-screen design must be a working interactive prototype.',
      },
    ],
    rules: [
      'Use Figma Only — no other design tools allowed.',
      'No AI-powered design tools or AI-generated assets.',
      'All content must be original or properly licensed.',
      'Team members must be registered together before the event starts.',
      'Do not copy designs from publicly available portfolios without attribution.',
      'Judges\' decision is final.',
    ],
    important: [
      'Bring your own laptop with Figma installed and a stable internet connection.',
      'Round 1 results determine eligibility for Round 2.',
      'Screens must be exported as Figma prototype links — no image exports.',
      'Late submissions will not be accepted.',
    ],
  },
  'ai-battle': {
    slug: 'ai-battle',
    title: 'AI BATTLE',
    subtitle: 'Think Fast. Build Smart. Battle with AI.',
    category: 'Technical',
    icon: '✦',
    color: 'violet',
    tagline: 'AI Command Center',
    theme: { primary: '#8b5cf6', accent: '#c4b5fd', bg: '#0f0618', glow: 'rgba(139,92,246,.3)' },
    eventType: 'Team Event',
    teamSize: 'Suggested 20 Members',
    requirement: 'Laptop Required',
    duration: '2–3 Hours',
    heroVisual: 'ai-lab',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'pipeline', label: 'Development Pipeline' },
      { id: 'ecosystem', label: 'Tech Ecosystem' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Team Event' },
      { label: 'Team Size', value: 'Suggested 20 Members' },
      { label: 'Duration', value: '2–3 Hours' },
      { label: 'Tool', value: 'Any AI Tool' },
      { label: 'Hardware', value: 'Laptop Required' },
    ],
    overview: 'AI Battle is a team-based challenge where you build an end-to-end AI-powered solution under time pressure. From problem framing to live demo — prove your team can ship AI that works.',
    pipeline: [
      { step: '01', title: 'Problem', desc: 'Receive the problem statement. Define the AI use case and scope.' },
      { step: '02', title: 'Ideate', desc: 'Brainstorm approaches, select models, design the system architecture.' },
      { step: '03', title: 'Build', desc: 'Code the solution, train/fine-tune models, integrate APIs.' },
      { step: '04', title: 'Test', desc: 'Validate accuracy, fix bugs, optimize performance.' },
      { step: '05', title: 'Complete', desc: 'Polish UI, write documentation, prepare the demo.' },
      { step: '06', title: 'Demo', desc: 'Present your working solution to the judges.' },
    ],
    ecosystem: {
      languages: ['Python', 'JavaScript/TypeScript', 'Rust', 'Go'],
      frameworks: ['PyTorch', 'TensorFlow', 'LangChain', 'Transformers', 'FastAPI', 'Express'],
      aiTools: ['GPT-4', 'Claude', 'Gemini', 'Stable Diffusion', 'Whisper'],
      apis: ['OpenAI API', 'Google AI', 'Hugging Face', 'Replicate'],
      openSource: ['Hugging Face Hub', 'GitHub Copilot', 'Ollama', 'vLLM'],
    },
    evaluationTitle: 'Evaluation Criteria',
    evaluation: [
      { label: 'Innovation & Creativity', weight: 'High' },
      { label: 'AI Implementation', weight: 'High' },
      { label: 'Technical Implementation', weight: 'High' },
      { label: 'Functionality & Working', weight: 'High' },
      { label: 'UI/UX & User Experience', weight: 'Medium' },
      { label: 'Presentation & Demo', weight: 'Medium' },
    ],
    rules: [
      'Must be a registered team of 2–20 members.',
      'Working end-to-end solution required for demo.',
      'All AI models must have valid API keys or local setups.',
      'No pre-built solutions from prior events — must be built during the event.',
      'Open-source libraries are allowed with proper attribution.',
      'Judges\' decision is final.',
    ],
    important: [
      'Ensure all API keys and credentials are set up before the event.',
      'A working demo is mandatory — no static slides accepted.',
      'Bring chargers and backup internet (mobile hotspot).',
      'GitHub repository link must be shared before demo time.',
    ],
  },
  'paper-presentation': {
    slug: 'paper-presentation',
    title: 'PAPER PRESENTATION',
    subtitle: 'Research. Reveal. Reveal.',
    category: 'Technical',
    icon: '◈',
    color: 'blue',
    tagline: 'Premium Academic Research Journal',
    theme: { primary: '#3b82f6', accent: '#93c5fd', bg: '#0a0f1e', glow: 'rgba(59,130,246,.3)' },
    eventType: 'Individual / Team of 2–3 Members',
    requirement: 'Research Paper',
    duration: 'Varies by round',
    heroVisual: 'journal',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'topics', label: 'Topics' },
      { id: 'timeline', label: 'Submission Timeline' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Individual / Team (2–3)' },
      { label: 'Paper Type', value: 'Research Paper' },
      { label: 'Submission', value: 'PDF + PPT' },
      { label: 'Presentation', value: '10 Minutes + Q&A' },
    ],
    topics: [
      { title: 'Agentic AI: Autonomous Systems Beyond Chatbots', desc: 'Explore how autonomous AI agents are reshaping industries — from coding assistants to autonomous vehicles.' },
      { title: 'Quantum Computing and Its Impact on Cybersecurity', desc: 'How quantum algorithms threaten current encryption and what post-quantum cryptography offers.' },
      { title: 'Neuromorphic Computing: Building Brain-Inspired Hardware', desc: 'Chips that think like the brain — exploring Intel Loihi, IBM TrueNorth, and the future of edge AI.' },
    ],
    timeline: [
      { step: '01', title: 'Abstract Submission', date: 'Oct 1', detail: '250–300 words, PDF format' },
      { step: '02', title: 'Shortlisting', date: 'Oct 3', detail: 'Results announced on official channels' },
      { step: '03', title: 'Final PPT Submission', date: 'Oct 6, 6 PM', detail: 'PDF or PPTX, max 15 slides' },
      { step: '04', title: 'Presentation Day', date: 'Event Day', detail: '10 min presentation + Q&A' },
    ],
    evaluationTitle: 'Evaluation Criteria',
    evaluation: [
      { label: 'Content & Technical Depth', weight: 'High' },
      { label: 'Innovation & Originality', weight: 'High' },
      { label: 'Presentation Skills & Clarity', weight: 'High' },
      { label: 'PPT Design & Structure', weight: 'Medium' },
      { label: 'Q&A Handling', weight: 'Medium' },
    ],
    rules: [
      'Abstract must be 250–300 words, submitted as PDF.',
      'Shortlisted teams must submit final PPT by Oct 6, 6 PM.',
      'Presentation time: 10 minutes total (8 min + 2 min Q&A buffer).',
      'Original research only — plagiarism check will be enforced.',
      'Co-authored papers must list all team members.',
      'Judges\' decision is final.',
    ],
    important: [
      'All submissions via the official registration portal.',
      'Presentation slides must be uploaded before the deadline — no on-site submissions.',
      'Bring your own laptop for presentation.',
      'Use the provided template for PPT submission.',
    ],
  },
  'code-arena': {
    slug: 'code-arena',
    title: 'CODE ARENA',
    subtitle: 'Think Fast. Code Smart. Optimize Better. Compete to Win.',
    category: 'Technical',
    icon: '⌘',
    color: 'cyan',
    tagline: 'Competitive Programming Arena',
    theme: { primary: '#06b6d4', accent: '#67e8f9', bg: '#061018', glow: 'rgba(6,182,212,.3)' },
    eventType: 'Individual',
    requirement: 'Laptop Required',
    duration: '90 Minutes + Finals',
    heroVisual: 'terminal',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'rounds', label: 'Rounds' },
      { id: 'topics', label: 'Topics' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Individual' },
      { label: 'Duration', value: '90 Minutes + Finals' },
      { label: 'Language', value: 'Any Programming Language' },
      { label: 'Platform', value: 'Online IDE' },
    ],
    overview: 'Code Arena tests your problem-solving speed, algorithmic thinking, and code optimization skills across three difficulty tiers. Climb from Easy to Hard and earn your spot on the podium.',
    rounds: [
      { number: '01', title: 'ROUND 1 — EASY', desc: 'Basic programming and problem-solving. Focus on correct logic and clean code.', problems: 3 },
      { number: '02', title: 'ROUND 2 — MEDIUM', desc: 'Algorithm selection, logical thinking and optimization. Balance speed and efficiency.', problems: 3 },
      { number: '03', title: 'ROUND 3 — HARD', desc: 'Advanced problem-solving and optimized solutions. Only the best reach this round.', problems: 3 },
    ],
    topics: ['Arrays', 'Strings', 'Hash Maps', 'Two Pointers', 'Sliding Window', 'Stack', 'Queue', 'Binary Search', 'Linked List', 'Trees', 'Graphs', 'Heap', 'Intervals', 'Recursion', 'Backtracking', 'Dynamic Programming'],
    evaluationTitle: 'Evaluation Criteria',
    evaluation: [
      { label: 'Problem-Solving Accuracy', weight: 'High' },
      { label: 'Execution Time', weight: 'High' },
      { label: 'Time Taken to Solve', weight: 'Medium' },
      { label: 'Algorithm Efficiency', weight: 'High' },
      { label: 'Time Complexity', weight: 'Medium' },
      { label: 'Space Complexity', weight: 'Medium' },
    ],
    important: [
      'Top 3 scorers win prizes 🥇 🥈 🥉',
      'Online IDE provided — no local setup needed.',
      'All test cases must pass for credit.',
      'Tie-breaker: time taken to solve, then number of submissions.',
    ],
  },
  'ipl-auction': {
    slug: 'ipl-auction',
    title: 'IPL AUCTION',
    subtitle: 'Build Your Championship Squad.',
    category: 'Non-Technical',
    icon: '◉',
    color: 'orange',
    tagline: 'Professional Live Cricket Auction',
    theme: { primary: '#f97316', accent: '#fdba74', bg: '#1a0f06', glow: 'rgba(249,115,22,.3)' },
    eventType: 'Team Event',
    teamSize: 'Suggested 10 Members',
    requirement: 'Strategy & Budget Management',
    duration: '1.5–2 Hours',
    heroVisual: 'stadium',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'auction-flow', label: 'Auction Flow' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'rules', label: 'Rules' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Team Event' },
      { label: 'Team Size', value: 'Suggested 10 Members' },
      { label: 'Purse', value: 'Fixed Virtual Budget' },
      { label: 'Duration', value: '1.5–2 Hours' },
    ],
    overview: 'Own a cricket franchise in our IPL Auction. Bid strategically on players, manage your purse wisely, and build a championship squad within budget. The best-balanced team wins.',
    auctionFlow: [
      { step: '01', title: 'Player Introduced', desc: 'Each player is announced with base price and skills.' },
      { step: '02', title: 'Base Price', desc: 'Set by organizers based on player ratings.' },
      { step: '03', title: 'Bidding', desc: 'Teams place competitive bids in real-time auction rounds.' },
      { step: '04', title: 'Sold', desc: 'Highest bidder wins the player for their squad.' },
      { step: '05', title: 'Squad Building', desc: 'Finalize your 11-member squad within purse limit.' },
    ],
    evaluationTitle: 'Evaluation Criteria',
    evaluation: [
      { label: 'Squad Composition', weight: 'High' },
      { label: 'Budget Management', weight: 'High' },
      { label: 'Strategic Bidding', weight: 'High' },
      { label: 'Overall Strategy', weight: 'Medium' },
    ],
    rules: [
      'Fixed virtual purse — overspending is not allowed.',
      'Each team must build a squad of exactly 11 players.',
      'Minimum 4 batsmen, 3 bowlers, 2 all-rounders, 1 wicket-keeper.',
      'No traded players from other teams.',
      'Final squad locked 15 minutes before submission deadline.',
      'Judges\' decision is final.',
    ],
    important: [
      'Player stats and base prices will be provided at the start.',
      'Squad composition rules must be strictly followed.',
      'Budget tracker will be displayed in real-time during auction.',
      'Winning criteria: Balance + Strategy + Final Squad Strength.',
    ],
  },
  'free-fire': {
    slug: 'free-fire',
    title: 'FREE FIRE',
    subtitle: 'Survive. Strategize. Dominate.',
    category: 'Non-Technical',
    icon: '△',
    color: 'purple',
    tagline: 'Battle Royale',
    theme: { primary: '#a855f7', accent: '#d8b4fe', bg: '#140a1a', glow: 'rgba(168,85,247,.3)' },
    eventType: 'Team Event',
    teamSize: '4 Members',
    requirement: 'Mobile Device',
    duration: 'Match Duration ~15 Min',
    heroVisual: 'battlefield',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'gameplay', label: 'Gameplay Flow' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Team Event (4 Members)' },
      { label: 'Device', value: 'Own Mobile Device' },
      { label: 'Account', value: 'Registered in-game' },
      { label: 'Room', value: 'Custom Room' },
    ],
    overview: 'Squad up for Free Fire. Join the custom room, survive the shrinking zone, eliminate opponents, and be the last squad standing. Strategy and teamwork win.',
    gameplay: [
      { step: '01', title: 'Join Room', desc: 'Use the tournament code to join the custom match.' },
      { step: '02', title: 'Match Start', desc: 'Drop in, loot up, and position your squad.' },
      { step: '03', title: 'Survive', desc: 'Stay within the safe zone as it shrinks.' },
      { step: '04', title: 'Eliminate', desc: 'Take down enemy squads with strategy.' },
      { step: '05', title: 'Score', desc: 'Points based on placements and eliminations.' },
      { step: '06', title: 'Result', desc: 'Final ranking announced. Top squads win prizes.' },
    ],
    rules: [
      'Must use your own mobile device with Free Fire installed.',
      'Account must be registered and in good standing.',
      'Join the custom room within the specified time window.',
      'Follow announced game mode and settings.',
      'No teaming with opposing squads.',
      'No hacks, scripts, or modified clients.',
      'No intentional disruption or sabotage.',
      'Any violation leads to immediate disqualification.',
      'Administrators decision is final.',
    ],
    evaluationTitle: 'Winner Determination',
    evaluation: [
      { label: 'Final Placement', weight: 'High' },
      { label: 'Eliminations', weight: 'Medium' },
      { label: 'Survival Time', weight: 'Medium' },
      { label: 'Team Coordination', weight: 'Medium' },
    ],
    important: [
      'Squad must be registered together before the match.',
      'Custom room details shared 30 minutes before start.',
      'Any team not joining within 5 minutes of match start is disqualified.',
      'Prizes for top 3 squads.',
    ],
  },
  'mini-militia': {
    slug: 'mini-militia',
    title: 'MINI MILITIA',
    subtitle: 'Lock. Aim. Battle.',
    category: 'Non-Technical',
    icon: '▷',
    color: 'red',
    tagline: 'Arcade Combat',
    theme: { primary: '#ef4444', accent: '#fca5a5', bg: '#1a0606', glow: 'rgba(239,68,68,.3)' },
    eventType: 'Individual / Team',
    teamSize: '1–2 Members',
    requirement: 'Mobile Device',
    duration: 'Match Duration ~10 Min',
    heroVisual: 'arcade',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'gameplay', label: 'Gameplay Flow' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Individual / Team (1–2)' },
      { label: 'Device', value: 'Mobile Device' },
      { label: 'Duration', value: '~10 Min per match' },
      { label: 'Mode', value: 'Fixed Match Duration' },
    ],
    overview: 'Fast-paced arcade combat in Mini Militia. Quick reflexes, smart aiming, and tactical play determine the winner.',
    gameplay: [
      { step: '01', title: 'Lobby', desc: 'Register and wait for all participants to join.' },
      { step: '02', title: 'Match', desc: 'Enter the arena — your battle begins on count down.' },
      { step: '03', title: 'Battle', desc: 'Eliminate opponents while surviving.' },
      { step: '04', title: 'Score', desc: 'Points tallied based on eliminations and survival.' },
      { step: '05', title: 'Result', desc: 'Top scorers advance or win prizes.' },
    ],
    rules: [
      'Must use your own mobile device.',
      'Join the lobby on time — latecomers are disqualified.',
      'Fixed match duration — no extensions.',
      'No modified game versions or plugins.',
      'No hacks, cheats, or external assistance.',
      'No intentional teaming (if individual format).',
      'Tie-breaker: additional tie-breaker match will be played.',
    ],
    evaluationTitle: 'Winner Determination',
    evaluation: [
      { label: 'Score', weight: 'High' },
      { label: 'Eliminations', weight: 'Medium' },
      { label: 'Survival Time', weight: 'Medium' },
      { label: 'Accuracy', weight: 'Low' },
    ],
    important: [
      'Tie-breaker match will be arranged for tied scores.',
      'Server settings are standardized for fair play.',
      'All matches are recorded for dispute resolution.',
    ],
  },
  'treasure-hunt': {
    slug: 'treasure-hunt',
    title: 'TREASURE HUNT',
    subtitle: 'Follow the Clues. Find the Treasure.',
    category: 'Non-Technical',
    icon: '⌁',
    color: 'yellow',
    tagline: 'Adventure Map',
    theme: { primary: '#eab308', accent: '#fde047', bg: '#1a1406', glow: 'rgba(234,179,8,.3)' },
    eventType: 'Team Event',
    teamSize: '3–5 Members',
    requirement: 'Teamwork & Navigation',
    duration: '2–3 Hours',
    heroVisual: 'map',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'map', label: 'Route Map' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Team Event (3–5 Members)' },
      { label: 'Duration', value: '2–3 Hours' },
      { label: 'Area', value: 'Campus Grounds' },
      { label: 'Checkpoints', value: '4 Checkpoints' },
    ],
    overview: 'Your team receives a map and the first clue. Solve riddles, find checkpoints, collect pieces of the treasure map, and reach the final treasure before other teams.',
    map: [
      { step: 'START', desc: 'Receive your map and first clue at the starting point.' },
      { step: 'CHECKPOINT 1', desc: 'Solve the riddle to get the next clue coordinates.' },
      { step: 'CHECKPOINT 2', desc: 'Navigate to the hidden location. Team photo required.' },
      { step: 'CHECKPOINT 3', desc: 'Decode the cipher to reveal checkpoint 4 location.' },
      { step: 'TREASURE', desc: 'Find the final treasure chest. First team wins!' },
    ],
    rules: [
      'All team members must stay together at all times.',
      'No external help — solve clues as a team.',
      'No unauthorized online searches for answers.',
      'No interference with other teams.',
      'Respect college property — no damage or trespassing.',
      'Follow all safety instructions from organizers.',
      'QR codes at checkpoints must be scanned for verification.',
      'Judges decision is final.',
    ],
    evaluationTitle: 'Winner Determination',
    evaluation: [
      { label: 'Time to Complete', weight: 'High' },
      { label: 'All Checkpoints Visited', weight: 'High' },
      { label: 'Clue Accuracy', weight: 'Medium' },
      { label: 'Team Coordination', weight: 'Low' },
    ],
    important: [
      'First team to successfully complete the hunt wins.',
      'All checkpoints must be visited for eligibility.',
      'Wear comfortable shoes and bring water.',
      'Emergency contact numbers will be provided.',
    ],
  },
  'meme-creation': {
    slug: 'meme-creation',
    title: 'MEME CREATION',
    subtitle: 'Make Them Laugh.',
    category: 'Non-Technical',
    icon: '☻',
    color: 'pink',
    tagline: 'Internet Culture Studio',
    theme: { primary: '#ec4899', accent: '#f472b6', bg: '#1a0a14', glow: 'rgba(236,72,153,.3)' },
    eventType: 'Individual',
    requirement: 'Laptop/Phone',
    duration: '90 Minutes',
    heroVisual: 'social',
    sections: [
      { id: 'snapshot', label: 'Event Snapshot' },
      { id: 'overview', label: 'Event Overview' },
      { id: 'flow', label: 'Flow' },
      { id: 'rules', label: 'Rules' },
      { id: 'evaluation', label: 'Evaluation' },
      { id: 'important', label: 'Important Info' },
    ],
    meta: [
      { label: 'Format', value: 'Individual' },
      { label: 'Tool', value: 'Any Allowed Tool' },
      { label: 'Duration', value: '90 Minutes' },
      { label: 'Submission', value: 'Image/Video' },
    ],
    overview: 'Create the funniest, most creative meme based on the event prompt. Show your understanding of internet culture, humor timing, and visual creativity.',
    flow: [
      { step: '01', title: 'Prompt', desc: 'Receive the meme topic/prompt at the start.' },
      { step: '02', title: 'Idea', desc: 'Brainstorm concepts and find the humor angle.' },
      { step: '03', title: 'Create', desc: 'Design your meme using permitted tools.' },
      { step: '04', title: 'Submit', desc: 'Upload your meme before the deadline.' },
      { step: '05', title: 'Judge', desc: 'Judging begins. Audience favorites also counted.' },
    ],
    rules: [
      'Original meme only — no reposted memes.',
      'Must follow the given prompt exactly.',
      'Use permitted tools — no restriction on tool choice.',
      'AI/Internet usage according to organizer announcement.',
      'No copied memes from other events or social media.',
      'No previously created memes for this event.',
      'No offensive, discriminatory, vulgar, or inappropriate content.',
      'Judges decision is final.',
    ],
    evaluationTitle: 'Evaluation Criteria',
    evaluation: [
      { label: 'Creativity', weight: 'High' },
      { label: 'Humour', weight: 'High' },
      { label: 'Relevance', weight: 'High' },
      { label: 'Originality', weight: 'High' },
      { label: 'Presentation', weight: 'Medium' },
    ],
    important: [
      'Prompt will be revealed at the start of the event.',
      'You can use any meme format — image, video, carousel.',
      'All submissions are reviewed by a panel + audience vote.',
      'Copyright-free images only.',
    ],
  },
};

export function getEventBySlug(slug) {
  return eventsConfig[slug] || null;
}

export function getAllEventSlugs() {
  return Object.keys(eventsConfig);
}

export function getTechEvents() {
  return Object.values(eventsConfig).filter((e) => e.category === 'Technical');
}

export function getNonTechEvents() {
  return Object.values(eventsConfig).filter((e) => e.category === 'Non-Technical');
}
