export const events = [
  {name:'Paper Presentation', slug:'paper-presentation', category:'Technical', icon:'◈', color:'blue', description:'Turn sharp ideas into impact. Present, defend and inspire with your research.', tagline:'Ideas that deserve a stage.', format:'Team / Individual', participants:'1–3 participants', rounds:'Abstract screening + presentation', duration:'8 minutes + Q&A', venue:'[Venue]', rules:['A team may have up to three members.','Abstracts must be submitted before the deadline.','Decisions of the judges are final.']},
  {name:'AI Battle', slug:'ai-battle', category:'Technical', icon:'✦', color:'violet', description:'Build intelligent solutions under pressure in this high-energy AI showdown.', tagline:'Train. Think. Triumph.', format:'Team', participants:'2 participants', rounds:'Challenge briefs + finale', duration:'120 minutes', venue:'[Venue]', rules:['Bring a charged laptop and valid college ID.','Pre-trained models must be disclosed.','Teams must work only on the announced challenge.']},
  {name:'Code Arena', slug:'code-arena', category:'Technical', icon:'⌘', color:'cyan', description:'Logic meets velocity. Solve, ship and climb the live leaderboard.', tagline:'Every second is a statement.', format:'Individual', participants:'1 participant', rounds:'Qualifier + final', duration:'90 minutes', venue:'[Venue]', rules:['Use of external assistance is prohibited.','Submissions are evaluated by automated test cases.','Leaderboard rank determines advancement.']},
  {name:'Pixel Perfect', slug:'pixel-perfect', category:'Technical', icon:'◐', color:'pink', description:'Design interfaces with the polish, clarity and spark of a standout product.', tagline:'Make every pixel count.', format:'Individual', participants:'1 participant', rounds:'Design sprint', duration:'90 minutes', venue:'[Venue]', rules:['Design assets will be shared at the venue.','Original work only.','Submit the final file before the timer ends.']},
  {name:'IPL Action', slug:'ipl-action', category:'Non-Technical', icon:'◉', color:'orange', description:'Bring your cricket IQ, instincts and auction-room energy to the table.', tagline:'Think like a franchise.', format:'Team', participants:'2–4 participants', rounds:'Auction + strategy', duration:'60 minutes', venue:'[Venue]', rules:['Team decisions are final once placed.','The event host’s ruling is final.','All participants must remain present throughout.']},
  {name:'Game Event', slug:'game-event', category:'Non-Technical', icon:'△', color:'purple', description:'A fast, social challenge designed for thrill seekers and quick thinkers.', tagline:'Play loud. Play smart.', format:'Team / Individual', participants:'As announced', rounds:'Knockout rounds', duration:'[Duration]', venue:'[Venue]', rules:['Follow fair-play rules at all times.','Event equipment must be handled responsibly.','Organizers may disqualify misconduct.']},
  {name:'Meme Creation', slug:'meme-creation', category:'Non-Technical', icon:'☻', color:'pink', description:'The internet’s favorite art form, judged on wit, relevance and craft.', tagline:'Make the room laugh.', format:'Individual', participants:'1 participant', rounds:'Creation + showcase', duration:'45 minutes', venue:'[Venue]', rules:['Keep submissions appropriate for a college audience.','Use only supplied or open-to-use material.','Submit in the specified format.']},
  {name:'Treasure Hunt', slug:'treasure-hunt', category:'Non-Technical', icon:'⌁', color:'yellow', description:'Decode clues, discover paths and race to uncover the final treasure.', tagline:'The clues are calling.', format:'Team', participants:'2–4 participants', rounds:'Multi-location hunt', duration:'[Duration]', venue:'Campus grounds', rules:['Stay within the designated event area.','Do not tamper with clues or props.','The first verified finish wins.']}
];
export const team = [{name:'[Faculty Coordinator]',role:'Faculty Coordinator',meta:'Department of CSE & Data Science'},{name:'[Faculty Coordinator]',role:'Faculty Coordinator',meta:'Department of CSE & Data Science'},{name:'[Student Coordinator]',role:'Student Lead',meta:'Operations & Experience'},{name:'[Student Coordinator]',role:'Creative Lead',meta:'Design & Media'},{name:'[Student Coordinator]',role:'Events Lead',meta:'Technical Events'},{name:'[Student Coordinator]',role:'Outreach Lead',meta:'Community & Partnerships'}];
export const faqs = [['What is FENIX’26?','FENIX’26 is the annual technical and non-technical symposium organised by the Department of CSE & Data Science.'],['Who can participate?','College students who meet the event eligibility criteria can participate.'],['Can I choose multiple events?','Yes. Choose your preferred technical and non-technical events during registration.'],['How is the fee calculated?','The fee is based on participation type and whether your choices exceed 2 technical + 2 non-technical events.'],['Where are event rules available?','Every event has a dedicated detail page with its format, rules and coordinator contacts.']];
